name: Trigger CI/CD

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger CI/CD
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: axel-vair/ci-c
          event-type: trigger-cd
          token: ${{ secrets.GITHUB_TOKEN }}
